#!/bin/sh

# WARNING: You quite probably don't have the terminus font installed. 
# Use xfontsel or similar application to select other font you like, 
# and set the FONT variable throughout this source appropriately.
# Or, even better, install terminus, it is probably the best console font.

# First kill any old instances of the monitors that may have been running
# before
killall osd_monitors

# Limit stack usage, so we don't eat too much memory 
ulimit -s 32768

# A helper function to run osd_monitors with common parameters. It places the
# monitor to the top right, runs it on the background, and increments the
# vertical position for the next monitor.
Y=-14
monitors() {
	osd_monitors "$@" --font "$FONT" -t -r -o $Y -H 10 &
	Y=$((Y+INCREMENT))
}

# For the clock use a slightly bigger font
FONT='-xos4-terminus-medium-r-normal-*-*-200-*-*-c-*-paratype-pt154'
INCREMENT=30

# Clock
monitors -T clock -i 1 -c cyan --format '%H:%M'

# For the rest of the monitors use smaller font
FONT='-xos4-terminus-medium-r-normal-*-*-140-*-*-c-*-paratype-pt154'
INCREMENT=17

# Cpu activity monitor. 
monitors -T cpu -D cpu -i 3 --level-colors="0:green 50:yellow 80:orange" --format="cpu:%.0f%%"

# Memory usage monitor
monitors -T mem -i 3 --level-colors="0:green 50:yellow 80:red" --format="mem:%U%%"

# Swap activity monitor
monitors -T swapact -i 3 --level-colors="0:gray 10240:yellow 1024000:red" --format="swp:%iB/%oB"

# Network activity monitor. The name of the device must be passed to this
# script as a parameter. If it is not, this monitor is disabled.
[ -z $1 ] || monitors -T net -D "$1" -i 3 --level-colors="0:gray 10240:white 51200:yellow 102400:orange" --format=$1":%iB/%oB"

monitors -T bat --level-colors="0:red 25:orange 50:yellow 99:green"
